/* Generated by wayland-scanner 1.21.0 */

#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zdwl_output_v1_interface;

static const struct wl_interface *dwl_bar_ipc_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&zdwl_output_v1_interface,
	&wl_output_interface,
};

static const struct wl_message zdwl_manager_v1_requests[] = {
	{ "release", "", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "get_output", "no", dwl_bar_ipc_unstable_v1_types + 4 },
};

static const struct wl_message zdwl_manager_v1_events[] = {
	{ "tag", "s", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "layout", "s", dwl_bar_ipc_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zdwl_manager_v1_interface = {
	"zdwl_manager_v1", 1,
	2, zdwl_manager_v1_requests,
	2, zdwl_manager_v1_events,
};

static const struct wl_message zdwl_output_v1_requests[] = {
	{ "release", "", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "set_layout", "u", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "set_tags", "uu", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "set_client_tags", "uu", dwl_bar_ipc_unstable_v1_types + 0 },
};

static const struct wl_message zdwl_output_v1_events[] = {
	{ "toggle_visibility", "", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "active", "u", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "tag", "uuuu", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "layout", "u", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "title", "s", dwl_bar_ipc_unstable_v1_types + 0 },
	{ "frame", "", dwl_bar_ipc_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zdwl_output_v1_interface = {
	"zdwl_output_v1", 1,
	4, zdwl_output_v1_requests,
	6, zdwl_output_v1_events,
};

